import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import { terser } from 'rollup-plugin-terser';
import styles from 'rollup-plugin-styles';

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "src/plugin/main.ts",
  output: {
    dir: "./Editing-Toolbar-Test-Vault/.obsidian/plugins/editing-toolbar",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    typescript(),
    nodeResolve({
      browser: true,
    }),
    commonjs({ include: "node_modules/**" }),
    terser(),
    styles()
  ],
};
