import { EditorView } from "@codemirror/view";

export const aiTheme = EditorView.baseTheme({
  ".cm-ai-loading": {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginLeft: "6px",
    color: "var(--text-muted)",
    opacity: "0.85",
    pointerEvents: "none",
    userSelect: "none",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  ".cm-ai-loading-spinner": {
    width: "10px",
    height: "10px",
    border: "1.5px solid currentColor",
    borderRightColor: "transparent",
    borderRadius: "999px",
    animation: "cm-ai-spin 0.8s linear infinite",
    flexShrink: "0",
  },
  ".cm-ai-loading-label": {
    letterSpacing: "0.01em",
  },
  ".cm-ai-loading-pill": {
    gap: "5px",
    marginLeft: "8px",
    padding: "2px 8px",
    borderRadius: "999px",
    border: "1px solid var(--background-modifier-border)",
    background: "color-mix(in srgb, var(--background-secondary) 76%, transparent)",
    color: "var(--text-faint)",
    opacity: "1",
    fontSize: "11px",
    lineHeight: "1.2",
    verticalAlign: "middle",
    backdropFilter: "blur(6px)",
  },
  ".cm-ai-loading-pill .cm-ai-loading-spinner": {
    width: "8px",
    height: "8px",
    borderWidth: "1.25px",
    opacity: "0.9",
  },
  ".cm-ai-loading-pill .cm-ai-loading-label": {
    fontWeight: "500",
    letterSpacing: "0.02em",
  },
  "&dark .cm-ai-loading-pill": {
    background: "color-mix(in srgb, var(--background-secondary-alt) 72%, transparent)",
    borderColor: "var(--background-modifier-border-hover)",
  },
  ".cm-ai-ghost-text": {
    color: "#999",
    fontStyle: "italic",
    pointerEvents: "none",
    userSelect: "none",
  },
  ".cm-ai-ghost-rest": {
    display: "block",
    whiteSpace: "pre-wrap",
  },
  "&dark .cm-ai-ghost-text": {
    color: "#666",
  },
  ".cm-ai-result-panel.cm-tooltip": {
    background: "var(--background-primary)",
    backgroundColor: "var(--background-primary)",
    border: "1px solid var(--background-modifier-border)",
    borderRadius: "12px",
    boxShadow: "0 14px 40px rgba(0,0,0,0.16)",
    padding: "10px",
    minWidth: "320px",
    maxWidth: "520px",
    animation: "cm-ai-fade-in 0.15s ease-out",
  },
  ".cm-ai-result-header": {
    fontWeight: "600",
    marginBottom: "8px",
    color: "var(--text-normal)",
  },
  ".cm-ai-result-content": {
    whiteSpace: "pre-wrap",
    lineHeight: "1.6",
    color: "var(--text-normal)",
    minHeight: "1.6em",
    maxHeight: "260px",
    overflowY: "auto",
    userSelect: "text",
    cursor: "text",
  },
  ".cm-ai-result-actions": {
    display: "flex",
    gap: "8px",
    marginTop: "12px",
    flexWrap: "wrap",
  },
  ".cm-ai-btn": {
    border: "none",
    borderRadius: "8px",
    padding: "6px 10px",
    cursor: "pointer",
    fontSize: "12px",
  },
  ".cm-ai-btn-primary": {
    background: "var(--interactive-accent)",
    color: "var(--text-on-accent)",
  },
  ".cm-ai-btn-secondary": {
    background: "var(--background-secondary)",
    color: "var(--text-normal)",
  },
  ".cm-ai-btn-danger": {
    background: "var(--background-modifier-error)",
    color: "var(--text-on-accent)",
  },
});
