import { EditorView } from "@codemirror/view";

export const aiTheme = EditorView.baseTheme({
  ".cm-ai-loading": {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginLeft: "6px",
    color: "var(--text-muted)",
    opacity: "0.85",
    pointerEvents: "none",
    userSelect: "none",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  ".cm-ai-loading-spinner": {
    width: "10px",
    height: "10px",
    border: "1.5px solid currentColor",
    borderRightColor: "transparent",
    borderRadius: "999px",
    animation: "cm-ai-spin 0.8s linear infinite",
    flexShrink: "0",
  },
  ".cm-ai-loading-label": {
    letterSpacing: "0.01em",
  },
  ".cm-ai-ghost-text": {
    color: "#999",
    fontStyle: "italic",
    pointerEvents: "none",
    userSelect: "none",
  },
  ".cm-ai-ghost-rest": {
    display: "block",
    whiteSpace: "pre-wrap",
  },
  "&dark .cm-ai-ghost-text": {
    color: "#666",
  },
  ".cm-ai-toolbar": {
    background: "var(--background-primary)",
    border: "1px solid var(--background-modifier-border)",
    borderRadius: "10px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.12)",
    padding: "8px",
    maxWidth: "340px",
    maxHeight: "400px",
    overflowY: "auto",
    fontSize: "13px",
  },
  ".cm-ai-toolbar-input-row": {
    display: "flex",
    gap: "6px",
    marginBottom: "8px",
    paddingBottom: "8px",
    borderBottom: "1px solid var(--background-modifier-border)",
  },
  ".cm-ai-toolbar-input": {
    flex: "1",
    padding: "6px 10px",
    border: "1px solid var(--background-modifier-border)",
    borderRadius: "6px",
    fontSize: "13px",
    outline: "none",
    background: "var(--background-secondary)",
    color: "var(--text-normal)",
  },
  ".cm-ai-toolbar-submit": {
    padding: "6px 10px",
    background: "var(--interactive-accent)",
    color: "var(--text-on-accent)",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },
  ".cm-ai-toolbar-actions": {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  ".cm-ai-toolbar-group": {
    display: "flex",
    flexDirection: "column",
  },
  ".cm-ai-toolbar-group-label": {
    fontSize: "11px",
    fontWeight: "600",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    padding: "6px 8px 2px",
  },
  ".cm-ai-toolbar-action": {
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "6px 8px",
    background: "none",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    color: "var(--text-normal)",
    fontSize: "13px",
  },
  ".cm-ai-toolbar-action:hover": {
    background: "var(--background-modifier-hover)",
    color: "var(--interactive-accent)",
  },
  ".cm-ai-result-panel": {
    background: "var(--background-primary)",
    border: "1px solid var(--background-modifier-border)",
    borderRadius: "12px",
    boxShadow: "0 14px 40px rgba(0,0,0,0.16)",
    padding: "10px",
    minWidth: "320px",
    maxWidth: "520px",
    animation: "cm-ai-fade-in 0.15s ease-out",
  },
  ".cm-ai-result-header": {
    fontWeight: "600",
    marginBottom: "8px",
    color: "var(--text-normal)",
  },
  ".cm-ai-result-content": {
    whiteSpace: "pre-wrap",
    lineHeight: "1.6",
    color: "var(--text-normal)",
    maxHeight: "260px",
    overflowY: "auto",
  },
  ".cm-ai-result-actions": {
    display: "flex",
    gap: "8px",
    marginTop: "12px",
    flexWrap: "wrap",
  },
  ".cm-ai-btn": {
    border: "none",
    borderRadius: "8px",
    padding: "6px 10px",
    cursor: "pointer",
    fontSize: "12px",
  },
  ".cm-ai-btn-primary": {
    background: "var(--interactive-accent)",
    color: "var(--text-on-accent)",
  },
  ".cm-ai-btn-secondary": {
    background: "var(--background-secondary)",
    color: "var(--text-normal)",
  },
  ".cm-ai-btn-danger": {
    background: "var(--background-modifier-error)",
    color: "var(--text-on-accent)",
  },
});
