import { EditorView } from "@codemirror/view";

export const aiTheme = EditorView.baseTheme({
  ".cm-ai-loading": {
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    marginLeft: "8px",
    color: "var(--text-muted)",
    pointerEvents: "none",
    userSelect: "none",
    fontSize: "12px",
    whiteSpace: "nowrap",
    position: "relative",
  },
  ".cm-ai-loading-visual": {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "14px",
    height: "14px",
    flexShrink: "0",
    zIndex: "1",
  },
  ".cm-ai-loading-spinner": {
    width: "8px",
    height: "8px",
    borderRadius: "999px",
    background: "linear-gradient(135deg, color-mix(in srgb, white 18%, var(--interactive-accent)), var(--interactive-accent))",
    boxShadow: "0 0 0 1px color-mix(in srgb, var(--interactive-accent) 22%, transparent), 0 0 12px color-mix(in srgb, var(--interactive-accent) 30%, transparent)",
    animation: "cm-ai-breathe 1.8s ease-in-out infinite",
    flexShrink: "0",
    position: "relative",
    zIndex: "1",
  },
  ".cm-ai-loading-glow": {
    position: "absolute",
    inset: "-4px",
    borderRadius: "999px",
    background: "radial-gradient(circle, color-mix(in srgb, var(--interactive-accent) 38%, transparent) 0%, color-mix(in srgb, var(--interactive-accent) 18%, transparent) 45%, transparent 75%)",
    filter: "blur(0.5px)",
    opacity: "0.72",
    animation: "cm-ai-glow 1.8s ease-in-out infinite",
    pointerEvents: "none",
  },
  ".cm-ai-loading-label": {
    letterSpacing: "0.02em",
    position: "relative",
    zIndex: "1",
    fontWeight: "500",
    animation: "cm-ai-label-breathe 1.8s ease-in-out infinite",
  },
  ".cm-ai-loading-sheen": {
    position: "absolute",
    inset: "-1px",
    borderRadius: "999px",
    background: "linear-gradient(115deg, transparent 0%, transparent 34%, color-mix(in srgb, white 70%, transparent) 48%, transparent 62%, transparent 100%)",
    transform: "translateX(-140%)",
    opacity: "0",
    animation: "cm-ai-sheen 2.8s ease-in-out infinite",
    pointerEvents: "none",
    mixBlendMode: "screen",
  },
  ".cm-ai-loading-pill": {
    gap: "7px",
    marginLeft: "8px",
    padding: "4px 10px 4px 8px",
    borderRadius: "999px",
    border: "1px solid color-mix(in srgb, var(--interactive-accent) 18%, var(--background-modifier-border))",
    background: "linear-gradient(135deg, color-mix(in srgb, var(--background-secondary) 92%, transparent), color-mix(in srgb, var(--background-secondary-alt) 82%, transparent))",
    color: "var(--text-faint)",
    opacity: "1",
    fontSize: "11px",
    lineHeight: "1.2",
    verticalAlign: "middle",
    backdropFilter: "blur(8px)",
    overflow: "hidden",
    isolation: "isolate",
    boxShadow: "0 6px 20px color-mix(in srgb, var(--interactive-accent) 8%, transparent), inset 0 1px 0 color-mix(in srgb, white 18%, transparent)",
    animation: "cm-ai-pill-breathe 2.2s ease-in-out infinite",
  },
  ".cm-ai-loading-pill .cm-ai-loading-spinner": {
    opacity: "1",
  },
  ".cm-ai-loading-pill .cm-ai-loading-label": {
    color: "var(--text-muted)",
  },
  "&dark .cm-ai-loading-pill": {
    background: "linear-gradient(135deg, color-mix(in srgb, var(--background-secondary-alt) 84%, transparent), color-mix(in srgb, var(--background-primary) 88%, transparent))",
    borderColor: "color-mix(in srgb, var(--interactive-accent) 24%, var(--background-modifier-border-hover))",
    boxShadow: "0 8px 26px color-mix(in srgb, black 26%, transparent), 0 0 0 1px color-mix(in srgb, var(--interactive-accent) 10%, transparent), inset 0 1px 0 rgba(255,255,255,0.04)",
  },
  ".cm-ai-ghost-text": {
    color: "#999",
    fontStyle: "italic",
    pointerEvents: "none",
    userSelect: "none",
  },
  ".cm-ai-ghost-rest": {
    display: "block",
    whiteSpace: "pre-wrap",
  },
  "&dark .cm-ai-ghost-text": {
    color: "#666",
  },
  ".cm-ai-result-panel.cm-tooltip": {
    background: "var(--background-primary)",
    backgroundColor: "var(--background-primary)",
    border: "1px solid var(--background-modifier-border)",
    borderRadius: "12px",
    boxShadow: "0 14px 40px rgba(0,0,0,0.16)",
    padding: "10px",
    minWidth: "320px",
    maxWidth: "520px",
    animation: "cm-ai-fade-in 0.15s ease-out",
  },
  ".cm-ai-result-header": {
    fontWeight: "600",
    marginBottom: "8px",
    color: "var(--text-normal)",
  },
  ".cm-ai-result-content": {
    whiteSpace: "pre-wrap",
    lineHeight: "1.6",
    color: "var(--text-normal)",
    minHeight: "1.6em",
    maxHeight: "260px",
    overflowY: "auto",
    userSelect: "text",
    cursor: "text",
  },
  ".cm-ai-result-actions": {
    display: "flex",
    gap: "8px",
    marginTop: "12px",
    flexWrap: "wrap",
  },
  ".cm-ai-btn": {
    border: "none",
    borderRadius: "8px",
    padding: "6px 10px",
    cursor: "pointer",
    fontSize: "12px",
  },
  ".cm-ai-btn-primary": {
    background: "var(--interactive-accent)",
    color: "var(--text-on-accent)",
  },
  ".cm-ai-btn-secondary": {
    background: "var(--background-secondary)",
    color: "var(--text-normal)",
  },
  ".cm-ai-btn-danger": {
    background: "var(--background-modifier-error)",
    color: "var(--text-on-accent)",
  },
});
